import Head from "next/head";
import CreateExamForm from "../components/CreateExamForm";
import Footer from "../components/Footer";
import Header from "../components/Header";

// Done form: question-answer-rightAnswer - 14-10-2021

export default function CreateExam() {
	return (
		<div className="w-auto">
			<Head>
				<title>Exam</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Header />
			<div className="p-5 min-h-screen">
				<CreateExamForm />
			</div>
			<Footer />
		</div>
	);
}
